const watchlist = [
    {
        title: "The King's Man",
        release_date: 2021,
        trakt_rating: 0.68,
        runtime: "131 mins",
        watched: false,
        director: "Matthew Vaughn",
        genres: ["Action", "Adventure", "Thriller", "War"],
        country: "US",
        summary: "Witness the bloody origin.",
        synopsis: "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
        trakt_url: "https://trakt.tv/movies/the-king-s-man-2021",
        trailer: "http://youtube.com/watch?v=e82JHkkPw54",
        thumbnail: "https://walter.trakt.tv/images/movies/000/324/048/posters/thumb/d88a8e1066.jpg"
    },
    {
        title: "House of Gucci",
        release_date: 2021,
        trakt_rating: 0.68,
        runtime: "158 mins",
        watched: false,
        director: "Ridley Scott",
        genres: ["Drama", "Crime", "Thriller"],
        country: "US",
        summary: "A legacy worth killing for.",
        synopsis: "When Patrizia Reggiani, an outsider from humble beginnings, marries into the Gucci family, her unbridled ambition begins to unravel the family legacy and triggers a reckless spiral of betrayal, decadence, revenge, and ultimately…murder.",
        trakt_url: "https://trakt.tv/movies/house-of-gucci-2021",
        trailer: "http://youtube.com/watch?v=pGi3Bgn7U5U",
        thumbnail: "https://walter.trakt.tv/images/movies/000/481/862/posters/thumb/46061e6f3f.jpg"
    },
    {
        title: "Jackass Forever",
        release_date: 2022,
        trakt_rating: 0.67,
        runtime: "96 mins",
        watched: false,
        director: "Jeff Tremaine",
        genres: ["Comedy", "Documentary", "Action"],
        country: "US",
        summary: "Some people never learn.",
        synopsis: "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
        trakt_url: "https://trakt.tv/movies/jackass-forever-2022",
        trailer: "http://youtube.com/watch?v=FNq-QT2Jpng",
        thumbnail: "https://walter.trakt.tv/images/movies/000/490/879/posters/thumb/b23ab409b4.jpg"
    },
    {
        title: "Venom: Let There Be Carnage",
        release_date: 2021,
        trakt_rating: 0.64,
        runtime: "97 mins",
        watched: false,
        director: "Jeff Tremaine",
        genres: ["Action", "Science Fiction", "Superhero", "Adventure"],
        country: "US",
        summary: null,
        synopsis: "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        trakt_url: "https://trakt.tv/movies/venom-let-there-be-carnage-2021",
        trailer: "http://youtube.com/watch?v=-ezfi6FQ8Ds",
        thumbnail: "https://walter.trakt.tv/images/movies/000/429/764/posters/thumb/7d6f389127.jpg"
    },
    {
        title: "The Last Duel",
        release_date: 2021,
        trakt_rating: 0.72,
        runtime: "153 mins",
        watched: false,
        director: "Ridley Scott",
        genres: ["Drama", "History", "Action"],
        country: "US",
        summary: "The true story of a woman who defied a nation and made history.",
        synopsis: "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
        trakt_url: "https://trakt.tv/movies/the-last-duel-2021",
        trailer: "http://youtube.com/watch?v=mgygUwPJvYk",
        thumbnail: "https://walter.trakt.tv/images/movies/000/460/727/posters/thumb/9834b949dc.jpg"
    },
    {
        title: "King Richard",
        release_date: 2021,
        trakt_rating: 0.78,
        runtime: "145 mins",
        watched: false,
        director: "Reinaldo Marcus Green",
        genres: ["Drama", "History"],
        country: "US",
        summary: "Venus, Serena and a plan for greatness.",
        synopsis: "The story of how Richard Williams served as a coach to his daughters Venus and Serena, who will soon become two of the most legendary tennis players in history.",
        trakt_url: "https://trakt.tv/movies/king-richard-2021",
        trailer: "http://youtube.com/watch?v=BKP_0z52ZAw",
        thumbnail: "https://walter.trakt.tv/images/movies/000/458/405/posters/thumb/6cbe684f52.jpg"
    },
    {
        title: "Everything, Everything",
        release_date: 2017,
        trakt_rating: 0.74,
        runtime: "96 mins",
        watched: false,
        director: "Stella Meghie",
        genres: ["Drama", "Romance"],
        country: "US",
        summary: "Risk everything... for love.",
        synopsis: "A teenager who's lived a sheltered life because she's allergic to everything, falls for the boy who moves in next door.",
        trakt_url: "https://trakt.tv/movies/everything-everything-2017",
        trailer: "http://youtube.com/watch?v=0LyEE7eR0nM",
        thumbnail: "https://walter.trakt.tv/images/movies/000/261/699/posters/thumb/f59083999c.jpg"
    },
    {
        title: "The Power of the Dog",
        release_date: 2021,
        trakt_rating: 0.67,
        runtime: "127 mins",
        watched: false,
        director: "Jane Campion",
        genres: ["Drama", "Western"],
        country: "Australia",
        summary: null,
        synopsis: "A domineering but charismatic rancher wages a war of intimidation on his brother's new wife and her teen son, until long-hidden secrets come to light.",
        trakt_url: "https://trakt.tv/movies/the-power-of-the-dog-2021",
        trailer: "http://youtube.com/watch?v=LRDPo0CHrko",
        thumbnail: "https://walter.trakt.tv/images/movies/000/446/376/posters/thumb/84b9fa499c.jpg"
    }
]

export default watchlist;